name: Hello World

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
      - run: ip -br a
        shell: bash
  job2:
    runs-on: ubuntu-26.04
    steps:
      - run: get-date 
        shell: pwsh
  job3:
    runs-on: ubuntu-22.04
    needs:
      - job1
      - job2
    steps:
      - run: print("Hello from an inline Python script in a GitHub Action Workflow!")
        shell: python
  job4:
    runs-on: ubuntu-26.04
    needs:
      - job3
    steps:
      - run: ping 4.2.2.4 -c 5
        shell: pwsh
  job5:
    runs-on: ubuntu-26.04
    needs:
      - job1
    steps:
      - run: hostnamectl hostname
        shell: pwsh
      