name: Hello World

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
  say-hello-inline-pwsh:
    runs-on: ubuntu-26.04
    steps:
      - run: Write-Host "hello works" -ForegroundColor green
        shell: pwsh
  say-hello-inline-python:
    runs-on: ubuntu-22.04
    steps:
      - run: print("Hello from an inline Python script in a GitHub Action Workflow!")
        shell: python