# .github/workflows/run-nginx.yml
name: Run Nginx Container

on:
  push:
    branches: ["main"]

jobs:
  run-docker:
    runs-on: self-hosted
    steps:
      - name: Run Nginx container
        run: sudo docker run nginx