# .github/workflows/run-nginx.yml
name: Run my custome command on remote host

on:
  push:
    branches: ["main"]

jobs:
  run-docker:
    runs-on: self-hosted
    steps:
      - name: Run Command
        run: mkdir /home/sysadmin/runer_2