# .github/workflows/run-nginx.yml
name: Run Nginx Container

on:
  push:
    branches: ["main"]

jobs:
  run-docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ubuntu:front-end-V0.1 --file dockerfile/ubuntu-baseimage/server.Dockerfile dockerfile/ubuntu-baseimage/